dist: xenial
language: python
python:
  - "3.5"
env:
  - DB=sqlite3
before_install:
  - sudo apt-get install -y python3-dev libsqlite3-dev sqlcipher libsqlcipher-dev
install:
  - pip install pipenv
  - pipenv sync
script: pipenv run python tests/test_transferDB.py
_static