image: ubuntu1804

environment:
  matrix:
    - PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
    - PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
    - PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"

install:
- sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0x51716619e084dab9
- sudo bash -c "echo 'deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/' >> /etc/apt/sources.list"
- sudo apt-get install -y openjdk-11-jre-headless
- sudo apt-get install -y openjdk-11-jre 
- sudo apt-get install -y r-base sqlcipher libsqlcipher-dev
- sudo apt-get install -y r-cran-rjava
- sudo R CMD javareconf
- sudo echo "install.packages(c('openVA', 'CrossVA'), repos='https://cloud.r-project.org/'); q('no')" > Rpackages.R
- sudo Rscript Rpackages.R

test_script:
- cd /home/appveyor/projects/openva_pipeline/
- python -m unittest discover -s tests

build: off
