image: ubuntu1804

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "3.5"
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "3.6"
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "3.7"

stack: python %PYTHON%

install:
- sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0x51716619e084dab9
- sudo bash -c "echo 'deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/' >> /etc/apt/sources.list"
- sudo apt-get install -y r-base sqlite3 libsqlite3-dev sqlcipher libsqlcipher-dev python3-pip
- cd /usr/src
- sudo wget https://www.python.org/ftp/python/3.5.6/Python-3.5.6.tgz
- sudo tar xzf Python-3.5.6.tgz
- cd Python-3.5.6
- sudo ./configure
- sudo make install
- sudo R CMD javareconf
- sudo echo "install.packages(c('openVA', 'CrossVA'), repos='https://cloud.r-project.org/'); q('no')" > Rpackages.R
- sudo Rscript Rpackages.R
- cd /home/appveyor/projects/openva-pipeline/
- python3 --version
- python3 -m pip install -r requirements.txt

test_script:
- python3 -m unittest discover -s tests

build: off
