image: ubuntu1804

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: ubuntu1804
      PYTHON: "3.6"
      PYVERSION: "3.6.5"
    - APPVEYOR_BUILD_WORKER_IMAGE: ubuntu1804
      PYTHON: "3.6"
      PYVERSION: "3.6.8"
    - APPVEYOR_BUILD_WORKER_IMAGE: ubuntu1804
      PYTHON: "3.7"
      PYVERSION: "3.7.2"

#stack: python %PYTHON%

install:
- sudo apt-get update
- sudo apt-get upgrade -y
- sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0x51716619e084dab9
- sudo bash -c "echo 'deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/' >> /etc/apt/sources.list"
- sudo apt-get install -y r-base sqlcipher libsqlcipher-dev
- cd /opt/
- sudo wget https://www.python.org/ftp/python/$PYVERSION/Python-$PYVERSION.tar.xz
- sudo tar xf Python-$PYVERSION.tar.xz
- cd Python-$PYVERSION
- sudo ./configure --enable-loadable-sqlite-extensions && sudo make && sudo make altinstall
- sudo R CMD javareconf
- cd /home/appveyor/projects
- sudo echo "install.packages(c('openVA', 'CrossVA'), repos='https://cloud.r-project.org/'); q('no')" > Rpackages.R
- sudo Rscript Rpackages.R
- cd /home/appveyor/projects/openva-pipeline/
- /usr/local/bin/python$PYTHON --version
- sudo /usr/local/bin/pip$PYTHON install -r requirements.txt

test_script:
- /usr/local/bin/python$PYTHON -m unittest discover -s tests

build: off
